#!/usr/bin/env python3
"""
Export Mendix SDK enumerations to CSV format
This script connects to a Mendix project and exports all enumerations with their translations
"""
import csv
import sys
from pathlib import Path

def generate_export_script():
    """Generate TypeScript code for exporting enumerations from Mendix SDK"""
    
    ts_code = []
    ts_code.append("//")       
    ts_code.append("//      ███  ███  ███")
    ts_code.append("//      ███▄▄███▄▄███")
    ts_code.append("//       ███████████")
    ts_code.append("//       ████▀▀▀████     Mendix SDK enumeration export script")
    ts_code.append("//       ████   ████")
    ts_code.append("//     ███████████████")
    ts_code.append("//     CONVENT SYSTEMS")
    ts_code.append("//")
    ts_code.append("import { MendixPlatformClient } from 'mendixplatformsdk';")
    ts_code.append("import { domainmodels } from 'mendixmodelsdk';")
    ts_code.append("import { enumerations } from 'mendixmodelsdk';")
    ts_code.append("import * as fs from 'fs';")
    ts_code.append("")
    ts_code.append("// Type alias for easier access")
    ts_code.append("type EnumerationValue = enumerations.EnumerationValue;")
    ts_code.append("")
    ts_code.append("interface EnumRow {")
    ts_code.append("  EnumName: string;")
    ts_code.append("  ValueName: string;")
    ts_code.append("  Caption: string;")
    ts_code.append("  LanguageCode: string;")
    ts_code.append("}")
    ts_code.append("")
    ts_code.append("async function exportEnumerations(")
    ts_code.append("  projectId: string,")
    ts_code.append("  outputFile: string = 'exported_enums.csv',")
    ts_code.append("  moduleName?: string  // Optional: filter by module name")
    ts_code.append(") {")
    ts_code.append("  // Create a Platform SDK client. This will automatically read")
    ts_code.append("  // your Personal Access Token from the environment variable MENDIX_TOKEN.")
    ts_code.append("  const client = new MendixPlatformClient();")
    ts_code.append("  ")
    ts_code.append("  console.log('Getting app...');")
    ts_code.append("  const app = client.getApp(projectId);")
    ts_code.append("  ")
    ts_code.append("  console.log('Creating temporary working copy...');")
    ts_code.append("  const workingCopy = await app.createTemporaryWorkingCopy('main');")
    ts_code.append("")
    ts_code.append("  console.log('Loading model...');")
    ts_code.append("  const model = workingCopy.openModel();")
    ts_code.append("  ")
    ts_code.append("  console.log('Loading all enumerations...');")
    ts_code.append("  const allEnums = (await model).allEnumerations();")
    ts_code.append("  ")
    ts_code.append("  // Load each enumeration")
    ts_code.append("  for (const enumeration of allEnums) {")
    ts_code.append("    await enumeration.load();")
    ts_code.append("  }")
    ts_code.append("")
    ts_code.append("  const rows: EnumRow[] = [];")
    ts_code.append("")
    ts_code.append("  // Iterate through all enumerations")
    ts_code.append("  for (const enumeration of allEnums) {")
    ts_code.append("    const enumName = enumeration.name;")
    ts_code.append("    ")
    ts_code.append("    // qualifiedName is in format \"ModuleName.EnumerationName\"")
    ts_code.append("    const qualifiedName = enumeration.qualifiedName;")
    ts_code.append("    const enumModuleName = qualifiedName ? qualifiedName.split('.')[0] : 'Unknown';")
    ts_code.append("    ")
    ts_code.append("    // Filter by module if specified")
    ts_code.append("    if (moduleName && enumModuleName !== moduleName) {")
    ts_code.append("      console.log(`Skipping enumeration: ${enumModuleName}.${enumName} (not in module '${moduleName}')`);")
    ts_code.append("      continue;")
    ts_code.append("    }")
    ts_code.append("    ")
    ts_code.append("    console.log(`Processing enumeration: ${enumModuleName}.${enumName}`);")
    ts_code.append("    ")
    ts_code.append("    // Get all values in this enumeration")
    ts_code.append("    for (const enumValue of enumeration.values) {")
    ts_code.append("      const valueName = enumValue.name;")
    ts_code.append("      ")
    ts_code.append("      // Access caption property (available after enumeration is loaded)")
    ts_code.append("      // Cast to concrete type to access the caption property")
    ts_code.append("      const valueAsConcrete = enumValue as EnumerationValue;")
    ts_code.append("      const caption = valueAsConcrete.caption;")
    ts_code.append("      ")
    ts_code.append("      if (caption && caption.translations && caption.translations.length > 0) {")
    ts_code.append("        for (const translation of caption.translations) {")
    ts_code.append("          rows.push({")
    ts_code.append("            EnumName: enumName,")
    ts_code.append("            ValueName: valueName,")
    ts_code.append("            Caption: translation.text,")
    ts_code.append("            LanguageCode: translation.languageCode")
    ts_code.append("          });")
    ts_code.append("        }")
    ts_code.append("      } else {")
    ts_code.append("        // No translations, use value name as caption")
    ts_code.append("        rows.push({")
    ts_code.append("          EnumName: enumName,")
    ts_code.append("          ValueName: valueName,")
    ts_code.append("          Caption: valueName,")
    ts_code.append("          LanguageCode: 'en_US'")
    ts_code.append("        });")
    ts_code.append("      }")
    ts_code.append("    }")
    ts_code.append("  }")
    ts_code.append("")
    ts_code.append("  // Convert to CSV")
    ts_code.append("  const csvHeader = 'EnumName,ValueName,Caption,LanguageCode\\n';")
    ts_code.append("  const csvRows = rows.map(row => ")
    ts_code.append("    `${escapeCsv(row.EnumName)},${escapeCsv(row.ValueName)},${escapeCsv(row.Caption)},${escapeCsv(row.LanguageCode)}`")
    ts_code.append("  ).join('\\n');")
    ts_code.append("  ")
    ts_code.append("  const csvContent = csvHeader + csvRows;")
    ts_code.append("  fs.writeFileSync(outputFile, csvContent, 'utf-8');")
    ts_code.append("  ")
    ts_code.append("  console.log(`\\n✓ Exported ${rows.length} enumeration values to ${outputFile}`);")
    ts_code.append("  console.log(`  Found ${new Set(rows.map(r => r.EnumName)).size} enumerations`);")
    ts_code.append("}")
    ts_code.append("")
    ts_code.append("function escapeCsv(value: string): string {")
    ts_code.append("  if (value.includes(',') || value.includes('\"') || value.includes('\\n')) {")
    ts_code.append("    return `\"${value.replace(/\"/g, '\"\"')}\"`;")
    ts_code.append("  }")
    ts_code.append("  return value;")
    ts_code.append("}")
    ts_code.append("")
    ts_code.append("// Usage example:")
    ts_code.append("// Set environment variable: export MENDIX_TOKEN='your-personal-access-token'")
    ts_code.append("// Export all enumerations: exportEnumerations('project-id', 'output.csv')")
    ts_code.append("// Export from specific module: exportEnumerations('project-id', 'output.csv', 'MyModule')")
    ts_code.append("//   .catch(console.error);")
    ts_code.append("")
    ts_code.append("export { exportEnumerations };")
    
    return '\n'.join(ts_code)

def main():
    print("Generating Mendix SDK export script...")
    
    ts_code = generate_export_script()
    
    output_file = 'export_mendix_enums.ts'
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(ts_code)
    
    print(f"✓ Export script generated: {output_file}")
    print("\nTo use this script:")
    print("1. Set the MENDIX_TOKEN environment variable with your Personal Access Token")
    print("   export MENDIX_TOKEN='your-personal-access-token'")
    print("2. Add the script to your Mendix SDK TypeScript project")
    print("3. Import and call the exportEnumerations function with your project ID")
    print("4. The function will generate a CSV file with all enumerations")
    print("\nExample usage:")
    print("  import { exportEnumerations } from './export_mendix_enums';")
    print("  exportEnumerations('project-id', 'output.csv');")

if __name__ == '__main__':
    main()
